[font]
size = 14.0

[font.normal]
# family = "FiraCode Nerd Font Mono"
family = "Liberation Mono"
# family = "Noto Sans Mono"
# family = "Maple Mono NF"
# family = "JetBrainsMono Nerd Font"
style = "regular"

[window]
opacity = 0.9

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true
